// Code generated by protoc-gen-go.
// source: protos/proto2/quota_service_proto2.proto
// DO NOT EDIT!

/*
Package quotaservice_proto2 is a generated protocol buffer package.

It is generated from these files:
	protos/proto2/quota_service_proto2.proto

It has these top-level messages:
	AllowRequest
	AllowResponse
*/
package quotaservice_proto2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AllowRequest_EmptyBucketPolicyOverride int32

const (
	AllowRequest_SERVER_DEFAULTS AllowRequest_EmptyBucketPolicyOverride = 0
	AllowRequest_WAIT            AllowRequest_EmptyBucketPolicyOverride = 1
	AllowRequest_REJECT          AllowRequest_EmptyBucketPolicyOverride = 2
)

var AllowRequest_EmptyBucketPolicyOverride_name = map[int32]string{
	0: "SERVER_DEFAULTS",
	1: "WAIT",
	2: "REJECT",
}
var AllowRequest_EmptyBucketPolicyOverride_value = map[string]int32{
	"SERVER_DEFAULTS": 0,
	"WAIT":            1,
	"REJECT":          2,
}

func (x AllowRequest_EmptyBucketPolicyOverride) Enum() *AllowRequest_EmptyBucketPolicyOverride {
	p := new(AllowRequest_EmptyBucketPolicyOverride)
	*p = x
	return p
}
func (x AllowRequest_EmptyBucketPolicyOverride) String() string {
	return proto.EnumName(AllowRequest_EmptyBucketPolicyOverride_name, int32(x))
}
func (x *AllowRequest_EmptyBucketPolicyOverride) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AllowRequest_EmptyBucketPolicyOverride_value, data, "AllowRequest_EmptyBucketPolicyOverride")
	if err != nil {
		return err
	}
	*x = AllowRequest_EmptyBucketPolicyOverride(value)
	return nil
}
func (AllowRequest_EmptyBucketPolicyOverride) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type AllowResponse_Status int32

const (
	AllowResponse_OK        AllowResponse_Status = 0
	AllowResponse_TIMED_OUT AllowResponse_Status = 1
	AllowResponse_REJECTED  AllowResponse_Status = 2
)

var AllowResponse_Status_name = map[int32]string{
	0: "OK",
	1: "TIMED_OUT",
	2: "REJECTED",
}
var AllowResponse_Status_value = map[string]int32{
	"OK":        0,
	"TIMED_OUT": 1,
	"REJECTED":  2,
}

func (x AllowResponse_Status) Enum() *AllowResponse_Status {
	p := new(AllowResponse_Status)
	*p = x
	return p
}
func (x AllowResponse_Status) String() string {
	return proto.EnumName(AllowResponse_Status_name, int32(x))
}
func (x *AllowResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AllowResponse_Status_value, data, "AllowResponse_Status")
	if err != nil {
		return err
	}
	*x = AllowResponse_Status(value)
	return nil
}
func (AllowResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type AllowRequest struct {
	BucketName        *string                                 `protobuf:"bytes,1,opt,name=bucket_name" json:"bucket_name,omitempty"`
	TokensRequested   *int32                                  `protobuf:"varint,2,opt,name=tokens_requested" json:"tokens_requested,omitempty"`
	EmptyBucketPolicy *AllowRequest_EmptyBucketPolicyOverride `protobuf:"varint,3,opt,name=empty_bucket_policy,enum=quotaservice.proto2.AllowRequest_EmptyBucketPolicyOverride" json:"empty_bucket_policy,omitempty"`
	XXX_unrecognized  []byte                                  `json:"-"`
}

func (m *AllowRequest) Reset()                    { *m = AllowRequest{} }
func (m *AllowRequest) String() string            { return proto.CompactTextString(m) }
func (*AllowRequest) ProtoMessage()               {}
func (*AllowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllowRequest) GetBucketName() string {
	if m != nil && m.BucketName != nil {
		return *m.BucketName
	}
	return ""
}

func (m *AllowRequest) GetTokensRequested() int32 {
	if m != nil && m.TokensRequested != nil {
		return *m.TokensRequested
	}
	return 0
}

func (m *AllowRequest) GetEmptyBucketPolicy() AllowRequest_EmptyBucketPolicyOverride {
	if m != nil && m.EmptyBucketPolicy != nil {
		return *m.EmptyBucketPolicy
	}
	return AllowRequest_SERVER_DEFAULTS
}

type AllowResponse struct {
	TokensGranted    *int32                `protobuf:"varint,1,opt,name=tokens_granted" json:"tokens_granted,omitempty"`
	Status           *AllowResponse_Status `protobuf:"varint,2,opt,name=status,enum=quotaservice.proto2.AllowResponse_Status" json:"status,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *AllowResponse) Reset()                    { *m = AllowResponse{} }
func (m *AllowResponse) String() string            { return proto.CompactTextString(m) }
func (*AllowResponse) ProtoMessage()               {}
func (*AllowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllowResponse) GetTokensGranted() int32 {
	if m != nil && m.TokensGranted != nil {
		return *m.TokensGranted
	}
	return 0
}

func (m *AllowResponse) GetStatus() AllowResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return AllowResponse_OK
}

func init() {
	proto.RegisterType((*AllowRequest)(nil), "quotaservice.proto2.AllowRequest")
	proto.RegisterType((*AllowResponse)(nil), "quotaservice.proto2.AllowResponse")
	proto.RegisterEnum("quotaservice.proto2.AllowRequest_EmptyBucketPolicyOverride", AllowRequest_EmptyBucketPolicyOverride_name, AllowRequest_EmptyBucketPolicyOverride_value)
	proto.RegisterEnum("quotaservice.proto2.AllowResponse_Status", AllowResponse_Status_name, AllowResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for QuotaService service

type QuotaServiceClient interface {
	Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error)
}

type quotaServiceClient struct {
	cc *grpc.ClientConn
}

func NewQuotaServiceClient(cc *grpc.ClientConn) QuotaServiceClient {
	return &quotaServiceClient{cc}
}

func (c *quotaServiceClient) Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error) {
	out := new(AllowResponse)
	err := grpc.Invoke(ctx, "/quotaservice.proto2.QuotaService/Allow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QuotaService service

type QuotaServiceServer interface {
	Allow(context.Context, *AllowRequest) (*AllowResponse, error)
}

func RegisterQuotaServiceServer(s *grpc.Server, srv QuotaServiceServer) {
	s.RegisterService(&_QuotaService_serviceDesc, srv)
}

func _QuotaService_Allow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AllowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(QuotaServiceServer).Allow(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _QuotaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quotaservice.proto2.QuotaService",
	HandlerType: (*QuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allow",
			Handler:    _QuotaService_Allow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x69, 0x95, 0x06, 0xae, 0x80, 0xcd, 0x90, 0x98, 0xea, 0x4a, 0xbb, 0xc2, 0x85, 0x25,
	0xe9, 0xce, 0xb8, 0x42, 0x19, 0x12, 0xfc, 0x09, 0xd8, 0x16, 0x75, 0x37, 0x56, 0x98, 0x18, 0x02,
	0x74, 0xca, 0xcc, 0x14, 0xc3, 0x63, 0xf8, 0x84, 0xbe, 0x8a, 0xed, 0x4c, 0x17, 0x2e, 0x54, 0x56,
	0xb7, 0xb9, 0xa7, 0xe7, 0xdc, 0xef, 0x0c, 0x74, 0x52, 0xce, 0x24, 0x13, 0x5d, 0x35, 0xfc, 0xee,
	0x3a, 0x63, 0x32, 0x26, 0x82, 0xf2, 0xcd, 0x7c, 0x4a, 0x89, 0x5e, 0x7a, 0x6a, 0xa0, 0xb6, 0xd2,
	0x4a, 0x49, 0xef, 0x7c, 0xf7, 0xcb, 0x80, 0x46, 0x6f, 0xb9, 0x64, 0x1f, 0x01, 0x5d, 0x67, 0x54,
	0x48, 0xd4, 0x86, 0x83, 0xb7, 0x6c, 0xba, 0xa0, 0x92, 0x24, 0xf1, 0x8a, 0x3a, 0xc6, 0xa9, 0xd1,
	0xa9, 0x23, 0x07, 0x6c, 0xc9, 0x16, 0x34, 0x11, 0x84, 0xeb, 0xdf, 0xe8, 0xcc, 0x31, 0x73, 0xa5,
	0x8a, 0x5e, 0xa0, 0x4d, 0x57, 0xa9, 0xdc, 0x92, 0xd2, 0x94, 0xb2, 0xe5, 0x7c, 0xba, 0x75, 0xf6,
	0x72, 0xb1, 0xe5, 0x5f, 0x79, 0xbf, 0x9c, 0xf4, 0x7e, 0x9e, 0xf3, 0x70, 0x61, 0xbe, 0x56, 0xde,
	0xb1, 0xb2, 0x8e, 0x36, 0x94, 0xf3, 0xf9, 0x8c, 0xba, 0x03, 0x38, 0xfe, 0x53, 0xcc, 0x29, 0x0f,
	0x43, 0x1c, 0x3c, 0xe1, 0x80, 0xf4, 0xf1, 0xa0, 0x37, 0xb9, 0x8f, 0x42, 0xbb, 0x82, 0x6a, 0xb0,
	0xff, 0xdc, 0x1b, 0x46, 0xb6, 0x81, 0x00, 0xac, 0x00, 0xdf, 0xe2, 0x9b, 0xc8, 0x36, 0xdd, 0x4f,
	0x03, 0x9a, 0xe5, 0x49, 0x91, 0xb2, 0x44, 0x50, 0x74, 0x04, 0xad, 0xb2, 0xcd, 0x3b, 0x8f, 0x93,
	0xa2, 0x8b, 0xa1, 0xba, 0x5c, 0x82, 0x25, 0x64, 0x2c, 0x33, 0xa1, 0xba, 0xb5, 0xfc, 0xf3, 0xff,
	0xf0, 0x75, 0x96, 0x17, 0x2a, 0x83, 0x7b, 0x01, 0x96, 0xfe, 0x42, 0x16, 0x98, 0xa3, 0xbb, 0x1c,
	0xa6, 0x09, 0xf5, 0x68, 0xf8, 0x80, 0xfb, 0x64, 0x34, 0x29, 0x88, 0x1a, 0x50, 0xd3, 0x44, 0xb8,
	0x6f, 0x9b, 0xfe, 0x2b, 0x34, 0x1e, 0x8b, 0xe8, 0x50, 0x47, 0xa3, 0x31, 0x54, 0x55, 0x2c, 0x3a,
	0xdb, 0xf9, 0x62, 0x27, 0xee, 0x6e, 0x2a, 0xb7, 0xf2, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xde, 0x13,
	0x81, 0x59, 0x17, 0x02, 0x00, 0x00,
}
