// Code generated by protoc-gen-go.
// source: quotaservice/protos/quota_service.proto
// DO NOT EDIT!

/*
Package quotaservice is a generated protocol buffer package.

It is generated from these files:
	quotaservice/protos/quota_service.proto

It has these top-level messages:
	AllowRequest
	AllowResponse
*/
package quotaservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AllowRequest_EmptyBucketPolicyOverride int32

const (
	AllowRequest_SERVER_DEFAULTS AllowRequest_EmptyBucketPolicyOverride = 0
	AllowRequest_WAIT            AllowRequest_EmptyBucketPolicyOverride = 1
	AllowRequest_REJECT          AllowRequest_EmptyBucketPolicyOverride = 2
)

var AllowRequest_EmptyBucketPolicyOverride_name = map[int32]string{
	0: "SERVER_DEFAULTS",
	1: "WAIT",
	2: "REJECT",
}
var AllowRequest_EmptyBucketPolicyOverride_value = map[string]int32{
	"SERVER_DEFAULTS": 0,
	"WAIT":            1,
	"REJECT":          2,
}

func (x AllowRequest_EmptyBucketPolicyOverride) String() string {
	return proto.EnumName(AllowRequest_EmptyBucketPolicyOverride_name, int32(x))
}
func (AllowRequest_EmptyBucketPolicyOverride) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type AllowResponse_Status int32

const (
	AllowResponse_OK        AllowResponse_Status = 0
	AllowResponse_TIMED_OUT AllowResponse_Status = 1
	AllowResponse_REJECTED  AllowResponse_Status = 2
)

var AllowResponse_Status_name = map[int32]string{
	0: "OK",
	1: "TIMED_OUT",
	2: "REJECTED",
}
var AllowResponse_Status_value = map[string]int32{
	"OK":        0,
	"TIMED_OUT": 1,
	"REJECTED":  2,
}

func (x AllowResponse_Status) String() string {
	return proto.EnumName(AllowResponse_Status_name, int32(x))
}
func (AllowResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type AllowRequest struct {
	BucketName        string                                 `protobuf:"bytes,1,opt,name=bucket_name" json:"bucket_name,omitempty"`
	TokensRequested   int32                                  `protobuf:"varint,2,opt,name=tokens_requested" json:"tokens_requested,omitempty"`
	EmptyBucketPolicy AllowRequest_EmptyBucketPolicyOverride `protobuf:"varint,3,opt,name=empty_bucket_policy,enum=quotaservice.AllowRequest_EmptyBucketPolicyOverride" json:"empty_bucket_policy,omitempty"`
}

func (m *AllowRequest) Reset()                    { *m = AllowRequest{} }
func (m *AllowRequest) String() string            { return proto.CompactTextString(m) }
func (*AllowRequest) ProtoMessage()               {}
func (*AllowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AllowResponse struct {
	TokensGranted int32                `protobuf:"varint,1,opt,name=tokens_granted" json:"tokens_granted,omitempty"`
	Status        AllowResponse_Status `protobuf:"varint,2,opt,name=status,enum=quotaservice.AllowResponse_Status" json:"status,omitempty"`
}

func (m *AllowResponse) Reset()                    { *m = AllowResponse{} }
func (m *AllowResponse) String() string            { return proto.CompactTextString(m) }
func (*AllowResponse) ProtoMessage()               {}
func (*AllowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*AllowRequest)(nil), "quotaservice.AllowRequest")
	proto.RegisterType((*AllowResponse)(nil), "quotaservice.AllowResponse")
	proto.RegisterEnum("quotaservice.AllowRequest_EmptyBucketPolicyOverride", AllowRequest_EmptyBucketPolicyOverride_name, AllowRequest_EmptyBucketPolicyOverride_value)
	proto.RegisterEnum("quotaservice.AllowResponse_Status", AllowResponse_Status_name, AllowResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for QuotaService service

type QuotaServiceClient interface {
	Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error)
}

type quotaServiceClient struct {
	cc *grpc.ClientConn
}

func NewQuotaServiceClient(cc *grpc.ClientConn) QuotaServiceClient {
	return &quotaServiceClient{cc}
}

func (c *quotaServiceClient) Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error) {
	out := new(AllowResponse)
	err := grpc.Invoke(ctx, "/quotaservice.QuotaService/Allow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QuotaService service

type QuotaServiceServer interface {
	Allow(context.Context, *AllowRequest) (*AllowResponse, error)
}

func RegisterQuotaServiceServer(s *grpc.Server, srv QuotaServiceServer) {
	s.RegisterService(&_QuotaService_serviceDesc, srv)
}

func _QuotaService_Allow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AllowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(QuotaServiceServer).Allow(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _QuotaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quotaservice.QuotaService",
	HandlerType: (*QuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allow",
			Handler:    _QuotaService_Allow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x69, 0x95, 0x06, 0xae, 0x05, 0x9b, 0x21, 0x31, 0x15, 0x37, 0xa6, 0x1b, 0xdd, 0x58,
	0x92, 0xea, 0x0b, 0x80, 0x0c, 0x09, 0xfe, 0x04, 0x69, 0x8b, 0x2e, 0x9b, 0x02, 0x37, 0x86, 0x00,
	0x9d, 0xd2, 0x99, 0x62, 0x78, 0x05, 0x9f, 0xd0, 0xc7, 0xb1, 0x9d, 0x76, 0xd1, 0x85, 0xb8, 0x6b,
	0xee, 0xbd, 0xe7, 0x9c, 0xef, 0x74, 0xe0, 0x66, 0x97, 0x32, 0x11, 0x72, 0x4c, 0xf6, 0xab, 0x05,
	0xf6, 0xe2, 0x84, 0x09, 0xc6, 0x7b, 0x72, 0x16, 0x94, 0x43, 0x5b, 0x0e, 0x89, 0x5e, 0x3d, 0xb4,
	0x7e, 0x14, 0xd0, 0xfb, 0x9b, 0x0d, 0xfb, 0x72, 0x71, 0x97, 0x22, 0x17, 0xa4, 0x03, 0x67, 0xf3,
	0x74, 0xb1, 0x46, 0x11, 0x44, 0xe1, 0x16, 0x4d, 0xe5, 0x5a, 0xb9, 0x6d, 0x12, 0x13, 0x0c, 0xc1,
	0xd6, 0x18, 0xf1, 0x20, 0x29, 0xce, 0x70, 0x69, 0xaa, 0xd9, 0xa6, 0x4e, 0xa6, 0xd0, 0xc1, 0x6d,
	0x2c, 0x0e, 0x41, 0x29, 0x8a, 0xd9, 0x66, 0xb5, 0x38, 0x98, 0x27, 0xd9, 0xb2, 0xed, 0x3c, 0xd8,
	0xd5, 0x2c, 0xbb, 0x9a, 0x63, 0xd3, 0x5c, 0x35, 0x90, 0xa2, 0x37, 0xa9, 0x99, 0xec, 0x31, 0x49,
	0x56, 0x4b, 0xb4, 0x46, 0x70, 0x79, 0x74, 0x99, 0xe1, 0x9d, 0x7b, 0xd4, 0x7d, 0xa7, 0x6e, 0x30,
	0xa4, 0xa3, 0xfe, 0xec, 0xc5, 0xf7, 0x8c, 0x1a, 0x69, 0xc0, 0xe9, 0x47, 0x7f, 0xec, 0x1b, 0x0a,
	0x01, 0xd0, 0x5c, 0xfa, 0x44, 0x1f, 0x7d, 0x43, 0xb5, 0xbe, 0x15, 0x68, 0x95, 0x91, 0x3c, 0x66,
	0x11, 0x47, 0x72, 0x01, 0xed, 0xb2, 0xc6, 0x67, 0x12, 0x46, 0x79, 0x09, 0x45, 0x96, 0x70, 0x40,
	0xe3, 0x22, 0x14, 0x29, 0x97, 0xa5, 0xda, 0x8e, 0xf5, 0x27, 0x77, 0x61, 0x62, 0x7b, 0xf2, 0xd2,
	0xba, 0x03, 0xad, 0xf8, 0x22, 0x1a, 0xa8, 0x93, 0xe7, 0x8c, 0xa2, 0x05, 0x4d, 0x7f, 0xfc, 0x4a,
	0x87, 0xc1, 0x64, 0x96, 0xa3, 0xe8, 0xd0, 0x28, 0x50, 0xe8, 0xd0, 0x50, 0x1d, 0x17, 0xf4, 0x69,
	0xee, 0xe9, 0x15, 0x9e, 0x64, 0x00, 0x75, 0x69, 0x4b, 0xba, 0xc7, 0xff, 0x51, 0xf7, 0xea, 0x1f,
	0x0e, 0xab, 0x36, 0xd7, 0xe4, 0x83, 0xde, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x44, 0x34,
	0xd9, 0xfb, 0x01, 0x00, 0x00,
}
