// Code generated by protoc-gen-go.
// source: protos/quota_service.proto
// DO NOT EDIT!

/*
Package quotaservice is a generated protocol buffer package.

It is generated from these files:
	protos/quota_service.proto

It has these top-level messages:
	AllowRequest
	AllowResponse
*/
package quotaservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AllowResponse_Status int32

const (
	AllowResponse_OK                                 AllowResponse_Status = 1
	AllowResponse_OK_WAIT                            AllowResponse_Status = 2
	AllowResponse_REJECTED_TIMEOUT                   AllowResponse_Status = 3
	AllowResponse_REJECTED_NO_BUCKET                 AllowResponse_Status = 4
	AllowResponse_REJECTED_TOO_MANY_BUCKETS          AllowResponse_Status = 5
	AllowResponse_REJECTED_TOO_MANY_TOKENS_REQUESTED AllowResponse_Status = 6
	AllowResponse_REJECTED_INVALID_REQUEST           AllowResponse_Status = 7
	AllowResponse_REJECTED_SERVER_ERROR              AllowResponse_Status = 8
)

var AllowResponse_Status_name = map[int32]string{
	1: "OK",
	2: "OK_WAIT",
	3: "REJECTED_TIMEOUT",
	4: "REJECTED_NO_BUCKET",
	5: "REJECTED_TOO_MANY_BUCKETS",
	6: "REJECTED_TOO_MANY_TOKENS_REQUESTED",
	7: "REJECTED_INVALID_REQUEST",
	8: "REJECTED_SERVER_ERROR",
}
var AllowResponse_Status_value = map[string]int32{
	"OK":                                 1,
	"OK_WAIT":                            2,
	"REJECTED_TIMEOUT":                   3,
	"REJECTED_NO_BUCKET":                 4,
	"REJECTED_TOO_MANY_BUCKETS":          5,
	"REJECTED_TOO_MANY_TOKENS_REQUESTED": 6,
	"REJECTED_INVALID_REQUEST":           7,
	"REJECTED_SERVER_ERROR":              8,
}

func (x AllowResponse_Status) Enum() *AllowResponse_Status {
	p := new(AllowResponse_Status)
	*p = x
	return p
}
func (x AllowResponse_Status) String() string {
	return proto.EnumName(AllowResponse_Status_name, int32(x))
}
func (x *AllowResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AllowResponse_Status_value, data, "AllowResponse_Status")
	if err != nil {
		return err
	}
	*x = AllowResponse_Status(value)
	return nil
}
func (AllowResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type AllowRequest struct {
	Namespace             *string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Name                  *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NumTokensRequested    *int64  `protobuf:"varint,3,opt,name=num_tokens_requested" json:"num_tokens_requested,omitempty"`
	MaxWaitMillisOverride *int64  `protobuf:"varint,4,opt,name=max_wait_millis_override" json:"max_wait_millis_override,omitempty"`
	XXX_unrecognized      []byte  `json:"-"`
}

func (m *AllowRequest) Reset()                    { *m = AllowRequest{} }
func (m *AllowRequest) String() string            { return proto.CompactTextString(m) }
func (*AllowRequest) ProtoMessage()               {}
func (*AllowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllowRequest) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

func (m *AllowRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *AllowRequest) GetNumTokensRequested() int64 {
	if m != nil && m.NumTokensRequested != nil {
		return *m.NumTokensRequested
	}
	return 0
}

func (m *AllowRequest) GetMaxWaitMillisOverride() int64 {
	if m != nil && m.MaxWaitMillisOverride != nil {
		return *m.MaxWaitMillisOverride
	}
	return 0
}

type AllowResponse struct {
	Status           *AllowResponse_Status `protobuf:"varint,1,opt,name=status,enum=quotaservice.AllowResponse_Status" json:"status,omitempty"`
	NumTokensGranted *int64                `protobuf:"varint,2,opt,name=num_tokens_granted" json:"num_tokens_granted,omitempty"`
	WaitMillis       *int64                `protobuf:"varint,3,opt,name=wait_millis" json:"wait_millis,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *AllowResponse) Reset()                    { *m = AllowResponse{} }
func (m *AllowResponse) String() string            { return proto.CompactTextString(m) }
func (*AllowResponse) ProtoMessage()               {}
func (*AllowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllowResponse) GetStatus() AllowResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return AllowResponse_OK
}

func (m *AllowResponse) GetNumTokensGranted() int64 {
	if m != nil && m.NumTokensGranted != nil {
		return *m.NumTokensGranted
	}
	return 0
}

func (m *AllowResponse) GetWaitMillis() int64 {
	if m != nil && m.WaitMillis != nil {
		return *m.WaitMillis
	}
	return 0
}

func init() {
	proto.RegisterType((*AllowRequest)(nil), "quotaservice.AllowRequest")
	proto.RegisterType((*AllowResponse)(nil), "quotaservice.AllowResponse")
	proto.RegisterEnum("quotaservice.AllowResponse_Status", AllowResponse_Status_name, AllowResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for QuotaService service

type QuotaServiceClient interface {
	Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error)
}

type quotaServiceClient struct {
	cc *grpc.ClientConn
}

func NewQuotaServiceClient(cc *grpc.ClientConn) QuotaServiceClient {
	return &quotaServiceClient{cc}
}

func (c *quotaServiceClient) Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error) {
	out := new(AllowResponse)
	err := grpc.Invoke(ctx, "/quotaservice.QuotaService/Allow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QuotaService service

type QuotaServiceServer interface {
	Allow(context.Context, *AllowRequest) (*AllowResponse, error)
}

func RegisterQuotaServiceServer(s *grpc.Server, srv QuotaServiceServer) {
	s.RegisterService(&_QuotaService_serviceDesc, srv)
}

func _QuotaService_Allow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AllowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(QuotaServiceServer).Allow(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _QuotaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quotaservice.QuotaService",
	HandlerType: (*QuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allow",
			Handler:    _QuotaService_Allow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xd1, 0x8e, 0x93, 0x40,
	0x18, 0x85, 0x85, 0x76, 0x59, 0xf7, 0x5f, 0x34, 0xe3, 0xef, 0x6a, 0x58, 0xd4, 0x64, 0xc3, 0x85,
	0xf1, 0x0a, 0x93, 0xbe, 0x01, 0xbb, 0x3b, 0x17, 0x88, 0xcb, 0x64, 0x07, 0xba, 0xc6, 0xab, 0x09,
	0x69, 0x27, 0x86, 0x08, 0x4c, 0xcb, 0x40, 0xeb, 0xf3, 0x79, 0xeb, 0x4b, 0x59, 0xa6, 0x58, 0x6b,
	0x34, 0x5e, 0xce, 0x39, 0xe7, 0xcf, 0x39, 0xf9, 0x06, 0xfc, 0x55, 0xab, 0x3a, 0xa5, 0xdf, 0xaf,
	0x7b, 0xd5, 0x15, 0x42, 0xcb, 0x76, 0x53, 0x2e, 0x64, 0x68, 0x44, 0x74, 0x8d, 0x38, 0x6a, 0x81,
	0x02, 0x37, 0xaa, 0x2a, 0xb5, 0xe5, 0x72, 0xdd, 0x4b, 0xdd, 0xe1, 0x33, 0x38, 0x6b, 0x8a, 0x5a,
	0xea, 0x55, 0xb1, 0x90, 0x9e, 0x75, 0x65, 0xbd, 0x3b, 0x43, 0x17, 0xa6, 0x83, 0xe4, 0xd9, 0xe6,
	0xf5, 0x1a, 0x2e, 0x9a, 0xbe, 0x16, 0x9d, 0xfa, 0x2a, 0x1b, 0x2d, 0xda, 0xfd, 0x99, 0x5c, 0x7a,
	0x93, 0x9d, 0x3b, 0xc1, 0x2b, 0xf0, 0xea, 0xe2, 0x9b, 0xd8, 0x16, 0x65, 0x27, 0xea, 0xb2, 0xaa,
	0x4a, 0x2d, 0xd4, 0x46, 0xb6, 0x6d, 0xb9, 0x94, 0xde, 0x74, 0x48, 0x04, 0xdf, 0x6d, 0x78, 0x32,
	0x36, 0xea, 0x95, 0x6a, 0xb4, 0xc4, 0x19, 0x38, 0xba, 0x2b, 0xba, 0x5e, 0x9b, 0xbe, 0xa7, 0xb3,
	0x20, 0x3c, 0x5e, 0x18, 0xfe, 0x11, 0x0e, 0x33, 0x93, 0x44, 0x1f, 0xf0, 0x68, 0xc5, 0x97, 0xb6,
	0x68, 0x86, 0x0d, 0xb6, 0xd9, 0xf0, 0x1c, 0xce, 0x8f, 0xfa, 0xf7, 0xc3, 0x82, 0x1f, 0x16, 0x38,
	0xe3, 0xad, 0x03, 0x36, 0x4b, 0x88, 0x85, 0xe7, 0x70, 0xca, 0x12, 0xf1, 0x29, 0x8a, 0x73, 0x62,
	0xe3, 0x05, 0x10, 0x4e, 0x3f, 0xd0, 0x9b, 0x9c, 0xde, 0x8a, 0x3c, 0xbe, 0xa3, 0x6c, 0x9e, 0x93,
	0x09, 0xbe, 0x04, 0x3c, 0xa8, 0x29, 0x13, 0xd7, 0xf3, 0x9b, 0x84, 0xe6, 0x64, 0x8a, 0x6f, 0xe0,
	0xf2, 0x77, 0x9a, 0x31, 0x71, 0x17, 0xa5, 0x9f, 0x47, 0x37, 0x23, 0x27, 0xf8, 0x16, 0x82, 0xbf,
	0xed, 0x9c, 0x25, 0x34, 0xcd, 0x04, 0xa7, 0xf7, 0x73, 0x9a, 0xed, 0x1c, 0xe2, 0xec, 0x58, 0x7a,
	0x87, 0x5c, 0x9c, 0x3e, 0x44, 0x1f, 0xe3, 0xdb, 0x5f, 0x3e, 0x39, 0xc5, 0x4b, 0x78, 0x71, 0x70,
	0x33, 0xca, 0x1f, 0x28, 0x17, 0x94, 0x73, 0xc6, 0xc9, 0xe3, 0x19, 0x07, 0xf7, 0x7e, 0x60, 0x94,
	0xed, 0x19, 0xe1, 0x35, 0x9c, 0x18, 0x4c, 0xe8, 0xff, 0x93, 0x9d, 0xf9, 0x23, 0xff, 0xd5, 0x7f,
	0xb8, 0x06, 0x8f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xce, 0x04, 0xde, 0x8c, 0x34, 0x02, 0x00,
	0x00,
}
