// Code generated by protoc-gen-go.
// source: protos/quota_service.proto
// DO NOT EDIT!

/*
Package quotaservice is a generated protocol buffer package.

It is generated from these files:
	protos/quota_service.proto

It has these top-level messages:
	AllowRequest
	AllowResponse
*/
package quotaservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AllowResponse_Status int32

const (
	AllowResponse_OK       AllowResponse_Status = 1
	AllowResponse_OK_WAIT  AllowResponse_Status = 2
	AllowResponse_REJECTED AllowResponse_Status = 3
	AllowResponse_FAILED   AllowResponse_Status = 4
)

var AllowResponse_Status_name = map[int32]string{
	1: "OK",
	2: "OK_WAIT",
	3: "REJECTED",
	4: "FAILED",
}
var AllowResponse_Status_value = map[string]int32{
	"OK":       1,
	"OK_WAIT":  2,
	"REJECTED": 3,
	"FAILED":   4,
}

func (x AllowResponse_Status) Enum() *AllowResponse_Status {
	p := new(AllowResponse_Status)
	*p = x
	return p
}
func (x AllowResponse_Status) String() string {
	return proto.EnumName(AllowResponse_Status_name, int32(x))
}
func (x *AllowResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AllowResponse_Status_value, data, "AllowResponse_Status")
	if err != nil {
		return err
	}
	*x = AllowResponse_Status(value)
	return nil
}
func (AllowResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type AllowRequest struct {
	Namespace             *string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Name                  *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NumTokensRequested    *int64  `protobuf:"varint,3,opt,name=num_tokens_requested" json:"num_tokens_requested,omitempty"`
	MaxWaitMillisOverride *int64  `protobuf:"varint,4,opt,name=max_wait_millis_override" json:"max_wait_millis_override,omitempty"`
	XXX_unrecognized      []byte  `json:"-"`
}

func (m *AllowRequest) Reset()                    { *m = AllowRequest{} }
func (m *AllowRequest) String() string            { return proto.CompactTextString(m) }
func (*AllowRequest) ProtoMessage()               {}
func (*AllowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllowRequest) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

func (m *AllowRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *AllowRequest) GetNumTokensRequested() int64 {
	if m != nil && m.NumTokensRequested != nil {
		return *m.NumTokensRequested
	}
	return 0
}

func (m *AllowRequest) GetMaxWaitMillisOverride() int64 {
	if m != nil && m.MaxWaitMillisOverride != nil {
		return *m.MaxWaitMillisOverride
	}
	return 0
}

type AllowResponse struct {
	Status           *AllowResponse_Status `protobuf:"varint,1,opt,name=status,enum=quotaservice.AllowResponse_Status" json:"status,omitempty"`
	NumTokensGranted *int64                `protobuf:"varint,2,opt,name=num_tokens_granted" json:"num_tokens_granted,omitempty"`
	WaitMillis       *int64                `protobuf:"varint,3,opt,name=wait_millis" json:"wait_millis,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *AllowResponse) Reset()                    { *m = AllowResponse{} }
func (m *AllowResponse) String() string            { return proto.CompactTextString(m) }
func (*AllowResponse) ProtoMessage()               {}
func (*AllowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllowResponse) GetStatus() AllowResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return AllowResponse_OK
}

func (m *AllowResponse) GetNumTokensGranted() int64 {
	if m != nil && m.NumTokensGranted != nil {
		return *m.NumTokensGranted
	}
	return 0
}

func (m *AllowResponse) GetWaitMillis() int64 {
	if m != nil && m.WaitMillis != nil {
		return *m.WaitMillis
	}
	return 0
}

func init() {
	proto.RegisterType((*AllowRequest)(nil), "quotaservice.AllowRequest")
	proto.RegisterType((*AllowResponse)(nil), "quotaservice.AllowResponse")
	proto.RegisterEnum("quotaservice.AllowResponse_Status", AllowResponse_Status_name, AllowResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for QuotaService service

type QuotaServiceClient interface {
	Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error)
}

type quotaServiceClient struct {
	cc *grpc.ClientConn
}

func NewQuotaServiceClient(cc *grpc.ClientConn) QuotaServiceClient {
	return &quotaServiceClient{cc}
}

func (c *quotaServiceClient) Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error) {
	out := new(AllowResponse)
	err := grpc.Invoke(ctx, "/quotaservice.QuotaService/Allow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QuotaService service

type QuotaServiceServer interface {
	Allow(context.Context, *AllowRequest) (*AllowResponse, error)
}

func RegisterQuotaServiceServer(s *grpc.Server, srv QuotaServiceServer) {
	s.RegisterService(&_QuotaService_serviceDesc, srv)
}

func _QuotaService_Allow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AllowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(QuotaServiceServer).Allow(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _QuotaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quotaservice.QuotaService",
	HandlerType: (*QuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allow",
			Handler:    _QuotaService_Allow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0xcf, 0x4f, 0x83, 0x30,
	0x14, 0xc7, 0xe5, 0x87, 0xe8, 0xde, 0xd0, 0x60, 0xf5, 0x40, 0xd0, 0xc3, 0xc2, 0xc9, 0x13, 0x26,
	0x5c, 0x3c, 0xa3, 0x62, 0x32, 0x67, 0xb2, 0xc8, 0x96, 0x78, 0x6c, 0x9a, 0xed, 0xc5, 0x10, 0x81,
	0xb2, 0xb6, 0x6c, 0xfe, 0x53, 0xfe, 0x8f, 0x42, 0xe1, 0x80, 0x89, 0xf1, 0xd6, 0x7e, 0xfa, 0x7d,
	0xf9, 0x7e, 0x5e, 0x21, 0xa8, 0x05, 0x57, 0x5c, 0xde, 0xed, 0x1a, 0xae, 0x18, 0x95, 0x28, 0xf6,
	0xf9, 0x06, 0x23, 0x0d, 0x89, 0xab, 0xe1, 0xc0, 0x42, 0x0e, 0x6e, 0x52, 0x14, 0xfc, 0x90, 0xe1,
	0xae, 0x41, 0xa9, 0xc8, 0x05, 0x4c, 0x2a, 0x56, 0xa2, 0xac, 0xd9, 0x06, 0x7d, 0x63, 0x66, 0xdc,
	0x4e, 0x88, 0x0b, 0x76, 0x87, 0x7c, 0x53, 0xdf, 0x6e, 0xe0, 0xaa, 0x6a, 0x4a, 0xaa, 0xf8, 0x27,
	0x56, 0x92, 0x8a, 0x7e, 0x0c, 0xb7, 0xbe, 0xd5, 0xbe, 0x5a, 0x64, 0x06, 0x7e, 0xc9, 0xbe, 0xe8,
	0x81, 0xe5, 0x8a, 0x96, 0x79, 0x51, 0xe4, 0x92, 0xf2, 0x3d, 0x0a, 0x91, 0x6f, 0xd1, 0xb7, 0xbb,
	0x44, 0xf8, 0x6d, 0xc0, 0xd9, 0xd0, 0x28, 0x6b, 0x5e, 0x49, 0x24, 0x31, 0x38, 0x52, 0x31, 0xd5,
	0x48, 0xdd, 0x77, 0x1e, 0x87, 0xd1, 0xd8, 0x30, 0xfa, 0x15, 0x8e, 0x56, 0x3a, 0x49, 0x02, 0x20,
	0x23, 0x8b, 0x0f, 0xc1, 0xaa, 0xce, 0xc1, 0xd4, 0x0e, 0x97, 0x30, 0x1d, 0xf5, 0xf7, 0x62, 0xe1,
	0x3d, 0x38, 0xc3, 0xa8, 0x03, 0xe6, 0x72, 0xe1, 0x19, 0x64, 0x0a, 0x27, 0xcb, 0x05, 0x7d, 0x4f,
	0xe6, 0x6b, 0xcf, 0x6c, 0x77, 0x3c, 0xcd, 0xd2, 0x97, 0xf4, 0x71, 0x9d, 0x3e, 0x79, 0x16, 0x01,
	0x70, 0x9e, 0x93, 0xf9, 0x6b, 0x7b, 0xb6, 0xe3, 0x0c, 0xdc, 0xb7, 0x4e, 0x67, 0xd5, 0xeb, 0x90,
	0x07, 0x38, 0xd6, 0x46, 0x24, 0xf8, 0x53, 0x53, 0x7f, 0x47, 0x70, 0xfd, 0xcf, 0x0a, 0xe1, 0xd1,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x38, 0xdd, 0x6a, 0x9f, 0x01, 0x00, 0x00,
}
