// Code generated by protoc-gen-go.
// source: quotaservice/protos/proto2/quota_service_proto2.proto
// DO NOT EDIT!

/*
Package quotaservice_proto2 is a generated protocol buffer package.

It is generated from these files:
	quotaservice/protos/proto2/quota_service_proto2.proto

It has these top-level messages:
	AllowRequest
	AllowResponse
*/
package quotaservice_proto2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AllowRequest struct {
	FromService      *string `protobuf:"bytes,1,opt,name=from_service" json:"from_service,omitempty"`
	ToService        *string `protobuf:"bytes,2,opt,name=to_service" json:"to_service,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AllowRequest) Reset()                    { *m = AllowRequest{} }
func (m *AllowRequest) String() string            { return proto.CompactTextString(m) }
func (*AllowRequest) ProtoMessage()               {}
func (*AllowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllowRequest) GetFromService() string {
	if m != nil && m.FromService != nil {
		return *m.FromService
	}
	return ""
}

func (m *AllowRequest) GetToService() string {
	if m != nil && m.ToService != nil {
		return *m.ToService
	}
	return ""
}

type AllowResponse struct {
	Granted          *bool  `protobuf:"varint,1,opt,name=granted" json:"granted,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AllowResponse) Reset()                    { *m = AllowResponse{} }
func (m *AllowResponse) String() string            { return proto.CompactTextString(m) }
func (*AllowResponse) ProtoMessage()               {}
func (*AllowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllowResponse) GetGranted() bool {
	if m != nil && m.Granted != nil {
		return *m.Granted
	}
	return false
}

func init() {
	proto.RegisterType((*AllowRequest)(nil), "quotaservice.proto2.AllowRequest")
	proto.RegisterType((*AllowResponse)(nil), "quotaservice.proto2.AllowResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for QuotaService service

type QuotaServiceClient interface {
	Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error)
}

type quotaServiceClient struct {
	cc *grpc.ClientConn
}

func NewQuotaServiceClient(cc *grpc.ClientConn) QuotaServiceClient {
	return &quotaServiceClient{cc}
}

func (c *quotaServiceClient) Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error) {
	out := new(AllowResponse)
	err := grpc.Invoke(ctx, "/quotaservice.proto2.QuotaService/Allow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QuotaService service

type QuotaServiceServer interface {
	Allow(context.Context, *AllowRequest) (*AllowResponse, error)
}

func RegisterQuotaServiceServer(s *grpc.Server, srv QuotaServiceServer) {
	s.RegisterService(&_QuotaService_serviceDesc, srv)
}

func _QuotaService_Allow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AllowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(QuotaServiceServer).Allow(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _QuotaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quotaservice.proto2.QuotaService",
	HandlerType: (*QuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allow",
			Handler:    _QuotaService_Allow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x2d, 0x2c, 0xcd, 0x2f,
	0x49, 0x2c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0x86,
	0x50, 0x46, 0xfa, 0x60, 0xa9, 0x78, 0xa8, 0x5c, 0x3c, 0x44, 0x50, 0x0f, 0x4c, 0x09, 0x09, 0x23,
	0x6b, 0x83, 0x88, 0x19, 0x29, 0x59, 0x70, 0xf1, 0x38, 0xe6, 0xe4, 0xe4, 0x97, 0x07, 0xa5, 0x16,
	0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x70, 0xf1, 0xa4, 0x15, 0xe5, 0xe7, 0xc2, 0x4c, 0x90, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x14, 0x12, 0xe2, 0xe2, 0x2a, 0xc9, 0x87, 0x8b, 0x31, 0x81, 0xc4, 0x94,
	0x14, 0xb8, 0x78, 0xa1, 0x3a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xf8, 0xb9, 0xd8, 0xd3,
	0x8b, 0x12, 0xf3, 0x4a, 0x52, 0x53, 0xc0, 0xba, 0x38, 0x8c, 0x12, 0xb8, 0x78, 0x02, 0x41, 0x56,
	0x06, 0x43, 0xf4, 0x09, 0x05, 0x70, 0xb1, 0x82, 0x75, 0x08, 0x29, 0xea, 0x61, 0x71, 0x8a, 0x1e,
	0xb2, 0x3b, 0xa4, 0x94, 0xf0, 0x29, 0x81, 0x58, 0xa8, 0xc4, 0x00, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x48, 0x1f, 0xbd, 0x08, 0x0a, 0x01, 0x00, 0x00,
}
