// Code generated by protoc-gen-go.
// source: protos/config/configs.proto
// DO NOT EDIT!

/*
Package quotaservice_configs is a generated protocol buffer package.

It is generated from these files:
	protos/config/configs.proto

It has these top-level messages:
	ServiceConfig
	NamespaceConfig
	BucketConfig
*/
package quotaservice_configs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Representations of configuration elements, for persisting and sharing across nodes.
type ServiceConfig struct {
	GlobalDefaultBucket *BucketConfig      `protobuf:"bytes,1,opt,name=global_default_bucket" json:"global_default_bucket,omitempty"`
	Namespaces          []*NamespaceConfig `protobuf:"bytes,2,rep,name=namespaces" json:"namespaces,omitempty"`
	Version             *int32             `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized    []byte             `json:"-"`
}

func (m *ServiceConfig) Reset()                    { *m = ServiceConfig{} }
func (m *ServiceConfig) String() string            { return proto.CompactTextString(m) }
func (*ServiceConfig) ProtoMessage()               {}
func (*ServiceConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceConfig) GetGlobalDefaultBucket() *BucketConfig {
	if m != nil {
		return m.GlobalDefaultBucket
	}
	return nil
}

func (m *ServiceConfig) GetNamespaces() []*NamespaceConfig {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *ServiceConfig) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type NamespaceConfig struct {
	Name                  *string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DefaultBucket         *BucketConfig   `protobuf:"bytes,2,opt,name=default_bucket" json:"default_bucket,omitempty"`
	DynamicBucketTemplate *BucketConfig   `protobuf:"bytes,3,opt,name=dynamic_bucket_template" json:"dynamic_bucket_template,omitempty"`
	MaxDynamicBuckets     *int32          `protobuf:"varint,4,opt,name=max_dynamic_buckets" json:"max_dynamic_buckets,omitempty"`
	Buckets               []*BucketConfig `protobuf:"bytes,5,rep,name=buckets" json:"buckets,omitempty"`
	XXX_unrecognized      []byte          `json:"-"`
}

func (m *NamespaceConfig) Reset()                    { *m = NamespaceConfig{} }
func (m *NamespaceConfig) String() string            { return proto.CompactTextString(m) }
func (*NamespaceConfig) ProtoMessage()               {}
func (*NamespaceConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NamespaceConfig) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NamespaceConfig) GetDefaultBucket() *BucketConfig {
	if m != nil {
		return m.DefaultBucket
	}
	return nil
}

func (m *NamespaceConfig) GetDynamicBucketTemplate() *BucketConfig {
	if m != nil {
		return m.DynamicBucketTemplate
	}
	return nil
}

func (m *NamespaceConfig) GetMaxDynamicBuckets() int32 {
	if m != nil && m.MaxDynamicBuckets != nil {
		return *m.MaxDynamicBuckets
	}
	return 0
}

func (m *NamespaceConfig) GetBuckets() []*BucketConfig {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type BucketConfig struct {
	Name                *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size                *int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	FillRate            *int64  `protobuf:"varint,3,opt,name=fill_rate" json:"fill_rate,omitempty"`
	WaitTimeoutMillis   *int64  `protobuf:"varint,4,opt,name=wait_timeout_millis" json:"wait_timeout_millis,omitempty"`
	MaxIdleMillis       *int64  `protobuf:"varint,5,opt,name=max_idle_millis" json:"max_idle_millis,omitempty"`
	MaxDebtMillis       *int64  `protobuf:"varint,6,opt,name=max_debt_millis" json:"max_debt_millis,omitempty"`
	MaxTokensPerRequest *int64  `protobuf:"varint,7,opt,name=max_tokens_per_request" json:"max_tokens_per_request,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *BucketConfig) Reset()                    { *m = BucketConfig{} }
func (m *BucketConfig) String() string            { return proto.CompactTextString(m) }
func (*BucketConfig) ProtoMessage()               {}
func (*BucketConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BucketConfig) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BucketConfig) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *BucketConfig) GetFillRate() int64 {
	if m != nil && m.FillRate != nil {
		return *m.FillRate
	}
	return 0
}

func (m *BucketConfig) GetWaitTimeoutMillis() int64 {
	if m != nil && m.WaitTimeoutMillis != nil {
		return *m.WaitTimeoutMillis
	}
	return 0
}

func (m *BucketConfig) GetMaxIdleMillis() int64 {
	if m != nil && m.MaxIdleMillis != nil {
		return *m.MaxIdleMillis
	}
	return 0
}

func (m *BucketConfig) GetMaxDebtMillis() int64 {
	if m != nil && m.MaxDebtMillis != nil {
		return *m.MaxDebtMillis
	}
	return 0
}

func (m *BucketConfig) GetMaxTokensPerRequest() int64 {
	if m != nil && m.MaxTokensPerRequest != nil {
		return *m.MaxTokensPerRequest
	}
	return 0
}

func init() {
	proto.RegisterType((*ServiceConfig)(nil), "quotaservice.configs.ServiceConfig")
	proto.RegisterType((*NamespaceConfig)(nil), "quotaservice.configs.NamespaceConfig")
	proto.RegisterType((*BucketConfig)(nil), "quotaservice.configs.BucketConfig")
}

var fileDescriptor0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0x4d, 0x4e, 0xfb, 0x30,
	0x10, 0xc5, 0x95, 0xa6, 0xfd, 0x57, 0x9d, 0x7f, 0xa1, 0xc2, 0x7c, 0x34, 0x52, 0x25, 0x54, 0x45,
	0x42, 0x62, 0x15, 0x24, 0x58, 0xc1, 0x0e, 0xba, 0x67, 0xc3, 0x01, 0x2c, 0x37, 0x99, 0x56, 0x56,
	0x9d, 0x38, 0xb5, 0x9d, 0xf2, 0x71, 0x18, 0x4e, 0xc0, 0xe9, 0x38, 0x01, 0xb6, 0x9b, 0x20, 0x5a,
	0x75, 0x91, 0x55, 0x94, 0xf7, 0xe6, 0xbd, 0xf9, 0x8d, 0x61, 0x52, 0x2a, 0x69, 0xa4, 0xbe, 0x49,
	0x65, 0xb1, 0xe0, 0xcb, 0xfa, 0xa3, 0x13, 0xaf, 0x92, 0xb3, 0x75, 0x25, 0x0d, 0xd3, 0xa8, 0x36,
	0x3c, 0xc5, 0xa4, 0xf6, 0xe2, 0xcf, 0x00, 0x8e, 0x5e, 0xb6, 0xda, 0xcc, 0x4b, 0xe4, 0x11, 0xce,
	0x97, 0x42, 0xce, 0x99, 0xa0, 0x19, 0x2e, 0x58, 0x25, 0x0c, 0x9d, 0x57, 0xe9, 0x0a, 0x4d, 0x14,
	0x4c, 0x83, 0xeb, 0xff, 0xb7, 0x71, 0x72, 0xa8, 0x27, 0x79, 0xf2, 0x33, 0x75, 0xc5, 0x3d, 0x40,
	0xc1, 0x72, 0xd4, 0x25, 0x4b, 0x51, 0x47, 0x9d, 0x69, 0x68, 0x73, 0x57, 0x87, 0x73, 0xcf, 0xcd,
	0x5c, 0x1d, 0x1d, 0x41, 0x7f, 0x83, 0x4a, 0x73, 0x59, 0x44, 0xa1, 0xdd, 0xd7, 0x8b, 0xbf, 0x03,
	0x18, 0xed, 0x0f, 0x0d, 0xa1, 0xeb, 0xfa, 0x3d, 0xd1, 0x80, 0x3c, 0xc0, 0xf1, 0x1e, 0x69, 0xa7,
	0x35, 0xe9, 0x0c, 0xc6, 0xd9, 0xbb, 0xed, 0xe2, 0x69, 0x9d, 0xa5, 0x06, 0xf3, 0x52, 0x30, 0x83,
	0x7e, 0x7d, 0xbb, 0x92, 0x09, 0x9c, 0xe6, 0xec, 0x8d, 0xee, 0x16, 0xe9, 0xa8, 0xeb, 0xf8, 0xc9,
	0x1d, 0xf4, 0x1b, 0xa1, 0xe7, 0x1f, 0xa2, 0x45, 0x63, 0xfc, 0x15, 0xc0, 0x70, 0x67, 0xc5, 0xee,
	0xc5, 0xf6, 0x4f, 0xf3, 0x0f, 0xf4, 0x77, 0x86, 0xe4, 0x04, 0x06, 0x0b, 0x2e, 0x04, 0x55, 0x0d,
	0x75, 0xe8, 0x88, 0x5e, 0x19, 0xb7, 0xc7, 0xf0, 0x1c, 0x65, 0x65, 0x68, 0x6e, 0x7d, 0xbe, 0x25,
	0x0a, 0xc9, 0x18, 0x46, 0x0e, 0x97, 0x67, 0x02, 0x1b, 0xa3, 0xf7, 0xd7, 0xc8, 0x70, 0xfe, 0x9b,
	0xf8, 0xe7, 0x8d, 0x4b, 0xb8, 0x70, 0x86, 0x91, 0x2b, 0x2c, 0x34, 0x2d, 0x51, 0x51, 0x85, 0xeb,
	0x0a, 0xb5, 0x89, 0xfa, 0xce, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xab, 0xba, 0x54, 0x78,
	0x02, 0x00, 0x00,
}
